### ISSUE TITLE
Fix merging rights on main for this repositories

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch-gcp#14]
I think the merging rights on main should be updated for this repository?

![Capture d’écran 2021-03-25 à 14 50 22](https://user-images.githubusercontent.com/44903069/112483591-73e6d900-8d79-11eb-8504-832aa16e069b.png)

⚠️ Should be done by a MeiliSearch team member.
@curquiza @eskombro

**Comment by curquiza** [comment]
I've protected the `main`:
- only the integration team can merge (push on `main`) since we don't have bors on this repo. For the moment you are in the integration team @nicolasvienot 😉 so you can merge
- the `pylint` check is required
- 1 reviewer is needed
- if you push another commit the approval is dismissed.

**Comment by curquiza** [comment]
If bors should be added, we should open another issue 🙂

**Comment by eskombro** [comment]
@nicolasvienot We can add bors as soon as we add the tests :)
